### ISSUE TITLE
using with user_ldap problems

### ISSUE THREAD

**Issue by jgribonvald** [owncloud/user_cas#13]
We are using this plugin with user_ldap and the plugin is registering user account after auth. Whereas we doesn't want to save the user from CAS attributes we want to keep LDAP user information and use CAS only to check user auth.

Is there a way to do solve this problem  ?

It seems this is a similar problem of https://github.com/owncloud/core/issues/7228

**Comment by guidtz** [comment]
Hello, I think I have the same problem. When I activate user_cas with "Link to LDAP backend" I cannot login with my users. I have this error in logs 
<code>
{"reqId":"jPjrAEmktoK5Ir7yKhkm","remoteAddr":"192.168.100.11","app":"user_ldap","message":"No LDAP Connection to server ","level":3,"time":"2015-08-12T13:28:20+00:00"}
{"reqId":"jPjrAEmktoK5Ir7yKhkm","remoteAddr":"192.168.100.11","app":"index","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Connection to LDAP server could not be established\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud\\\/www\\\/apps\\\/user_ldap\\\/lib\\\/access.php(729): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#1 \\\/var\\\/www\\\/cloud\\\/www\\\/apps\\\/user_ldap\\\/lib\\\/access.php(877): OCA\\\\user_ldap\\\\lib\\\\Access->executeSearch('', '', Array, NULL, NULL)\\n#2 \\\/var\\\/www\\\/cloud\\\/www\\\/apps\\\/user_ldap\\\/lib\\\/access.php(665): OCA\\\\user_ldap\\\\lib\\\\Access->search('', '', 'dn', NULL, NULL)\\n#3 \\\/var\\\/www\\\/cloud\\\/www\\\/apps\\\/user_ldap\\\/lib\\\/access.php(622): OCA\\\\user_ldap\\\\lib\\\\Access->searchUsers('', 'dn', NULL, NULL)\\n#4 \\\/var\\\/www\\\/cloud\\\/www\\\/apps\\\/user_cas\\\/lib\\\/ldap_backend_adapter.php(115): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfUsers('', 'dn')\\n#5 \\\/var\\\/www\\\/cloud\\\/www\\\/apps\\\/user_cas\\\/user_cas.php(127): OCA\\\\user_cas\\\\lib\\\\LdapBackendAdapter->getUuid('guillaume.chera...')\\n#6 \\\/var\\\/www\\\/cloud\\\/www\\\/lib\\\/private\\\/user\\\/manager.php(178): OC_USER_CAS->checkPassword('', '')\\n#7 \\\/var\\\/www\\\/cloud\\\/www\\\/lib\\\/private\\\/user\\\/session.php(217): OC\\\\User\\\\Manager->checkPassword('', '')\\n#8 \\\/var\\\/www\\\/cloud\\\/www\\\/lib\\\/private\\\/user.php(242): OC\\\\User\\\\Session->login('', '')\\n#9 \\\/var\\\/www\\\/cloud\\\/www\\\/apps\\\/user_cas\\\/appinfo\\\/app.php(50): OC_User::login('', '')\\n#10 \\\/var\\\/www\\\/cloud\\\/www\\\/lib\\\/private\\\/app.php(139): require_once('\\\/var\\\/www\\\/cloud....')\\n#11 \\\/var\\\/www\\\/cloud\\\/www\\\/lib\\\/private\\\/app.php(120): OC_App::requireAppFile('user_cas')\\n#12 \\\/var\\\/www\\\/cloud\\\/www\\\/lib\\\/private\\\/app.php(99): OC_App::loadApp('user_cas')\\n#13 \\\/var\\\/www\\\/cloud\\\/www\\\/lib\\\/base.php(843): OC_App::loadApps(Array)\\n#14 \\\/var\\\/www\\\/cloud\\\/www\\\/index.php(40): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud\\\/www\\\/apps\\\/user_ldap\\\/lib\\\/connection.php\",\"Line\":175}","level":4,"time":"2015-08-12T13:28:20+00:00"}
</code>

With owncloud 8.1

Sincerely
