### ISSUE TITLE
user_cas and LDAP does not let me login after installing

### ISSUE THREAD

**Issue by giannopk** [owncloud/user_cas#45]
I updated my installation from own cloud 7 gradually to own cloud 10. 
Then I installed user_cas. I already have LDAP configured and working.
However, when I try to login using CAS I cannot login and the following error appears.
To login, I click on the "login using CAS" button in the login screen. Then it redirects me to my cas service. I login to the cas service and it redirects me back in the login screen of own cloud 10, with the next error message.
Note that even if I am trying user_cas without the LDAP enabled, I still get an error.
I use own cloud 10 on centOS. 

The error message is: 

Internal server error

The server has encountered an internal server error and cannot complete your request.

Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.

More details can be found in the server log.

Technical info

    client IP: 10.7.250.2
    Request ID: WnwGnBE2mZZTWh8Yh0smcQAAAAU
    Type: Error
    Code: 0
    Message: Call to undefined method OC_User::login()
    File: /IS/web/hosting/hosts/owncloud/apps/user_cas/appinfo/app.php
    Line: 50

Trace

#0 /IS/web/hosting/hosts/owncloud/lib/private/legacy/app.php(242): require_once()
#1 /IS/web/hosting/hosts/owncloud/lib/private/legacy/app.php(193): OC_App::requireAppFile('user_cas')
#2 /IS/web/hosting/hosts/owncloud/lib/private/legacy/app.php(127): OC_App::loadApp('user_cas')
#3 /IS/web/hosting/hosts/owncloud/lib/private/legacy/user.php(128): OC_App::loadApps(Array)
#4 /IS/web/hosting/hosts/owncloud/lib/base.php(657): OC_User::setupBackends()
#5 /IS/web/hosting/hosts/owncloud/lib/base.php(998): OC::init()
#6 /IS/web/hosting/hosts/owncloud/index.php(54): require_once('/IS/web/hosting...')
#7 {main}

Note: I have even tried it in own cloud 9.1 and it gives me a blank login page on this version and a server error log:
[Thu Feb 08 10:52:56.793864 2018] [:error] [pid 15253] [client 10.7.250.2:51911] PHP Fatal error:  Call to undefined method OC_User::login() in /IS/web/hosting/hosts/owncloud/apps/user_cas/appinfo/app.php on line 50

Also note: I have tried it also in own cloud 9 and the error is:
[:error] [pid 20087] [client 10.7.250.2:52017] PHP Fatal error:  Class 'OCA\\user_cas\\lib\\LdapBackendAdapter' not found in /IS/web/hosting/hosts/owncloud/apps/user_cas/user_cas.php on line 111
[Thu Feb 08 11:20:17.190883 2018] [headers:debug] [pid 20087] mod_headers.c(823): AH01502: headers: ap_headers_output_filter()

**Comment by felixrupp** [comment]
Hi @giannopk 

The old user_cas app is broken since OC9. Since OC9 you should use my fork of [user_cas](https://github.com/felixrupp/user_cas), it is a complete rewrite on the base of OC9 coding guidelines.

You should use the latest version 1.4.x, it will work in OC9 and 10 WITHOUT user_ldap (user_ldap support has been dropped).
